Added SaiSudhaV
Binary-Cumates/Hacktoberfest-21-Open-First-PR pull request #22
Opened 2021-09-30 20:36 UTC by SaiSudhaV

2021-10-01 07:41 UTC, iamdevvalecha commented
@SaiSudhaV - Star this repository
- [![GitHub followers](https://img.shields.io/github/followers/iamdevvalecha.svg?label=Follow%20@iamdevvalecha&style=social)](https://github.com/iamdevvalecha/)

2021-10-01 07:42 UTC, iamdevvalecha requested changes

2021-10-01 07:42 UTC, iamdevvalecha commented on content/participant/saisudha.md
> +Portfolio: https://portfolios.talentsprint.com/~sudha_vadisina
please follow templete

2021-10-01 23:11 UTC, iamdevvalecha approved these changes

2021-10-02 09:33 UTC, CodingSpecies approved these changes

2021-10-02 09:33 UTC, merged

2021-10-02 09:33 UTC, CodingSpecies commented
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊